### ISSUE TITLE
Errors and Warnings with an install

### ISSUE THREAD

**Issue by drbkimmel** [vidriotech/activity-viewer2#14]
![BEKpipReqInstallERRORs](https://user-images.githubusercontent.com/3056409/94422051-7bc01a80-0154-11eb-9fc0-8049fc7ea23c.PNG)
ERRORs when installing pip requirements

![YarnInstallWarnings](https://user-images.githubusercontent.com/3056409/94422099-8aa6cd00-0154-11eb-9042-7376b78ed3a3.PNG)
Yarn warnings

![BEKPytestERRORS](https://user-images.githubusercontent.com/3056409/94422112-909cae00-0154-11eb-8541-94c65816413c.PNG)
Pytest ERRORS

**Comment by aliddell** [comment]
Should be resolved now. Keeping open until you confirm.
